### PR TITLE
Replace Travis With GitHub Deployment Workflow

### PR DESCRIPTION
**Pull request by daviesnathan**
This PR adds release and deployments capability to our existing GitHub Actions workflows.

- `build_and_test.yml` has been renamed to `test.yml` and includes all recent changes as well as logical comment blocks and adds a downstream workflow trigger via `repository_dispatch` on `master`
- `release.yml` brings semantic-release execution into Actions. This requires a Personal Access Token due to restrictions outlined in the `workflows/README` and as per below under Dependencies
- `deploy.yml` brings the final installation, configuration, packaging and deployment into Actions. Replicating some of the finer housekeeping tasks, directory structures and scripts from the previous deployment tooling. **Major change - releases on remote host are now named as per their tag, not the ID previously used by the old system.** `.deploy.yml` also includes generation of a Github Deployment for every deployment into production.

_Manual Triggers for Deployment Workflow_
**TL:DR, not possible via Github UI, needs to be triggered via API using PAT.** 

Sometimes may be necessary to run deployment manually - See `.github/workflows/README.md` for details and example CuRL request for triggering a deployment.

_Other minor notes:_
- Env vars are used within the deployment script to set out application directory structures and also the number of versions to keep should we wish to change them in the future.

### Dependencies:

- [x] Add all configuration secrets to the repository for the workflows
- [x] Create new deployment user on remote deployment target server
- [x] Update job secrets with deployment user credentials
- [x] @CalumTowers to generate a Personal Access Token with `repo:all` permissions and add to `secrets.PAT` for job triggers and releases.
- [x] @CalumTowers to generate a Slack Incoming Webhook for deployment notifications and set to `secrets.ACTIONS_SLACK_WEBHOOK`

### CODE REVIEW

**Comment by CalumTowers** [comment]
@daviesnathan PAT added

**Comment by daviesnathan** [comment]
Latest commit adds Slack notifications for deployment tasks as below:
Screenshot 2020-06-09 at 18 16 50

**Comment by CalumTowers** [comment]
@daviesnathan Slack webhook added as a secret

**Review by CalumTowers — DISMISSED** [review]
Happy that this can be deployed. Could do with being together for the first deployment to make sure everything ticks over as expected.

**Comment by AxonC** [comment]
@daviesnathan is this still ready to rumble?

**Comment by CalumTowers** [comment]
> @daviesnathan is this still ready to rumble?

It is, we just need to set some time aside to do the first deploy and make sure everything goes smoothly

**Comment by daviesnathan** [comment]
I'm going to have to update this to now post into Discord over Slack.

**Pull request merged**
