### PR TITLE
Training Staff Changes

### PR DESCRIPTION
**Pull request by inventor02**
https://community.vatsim.uk/news/united-kingdom/appointments-training-department-r323/

### CODE REVIEW

**Comment by inventor02** [comment]
@Keanu73 that is not a "Training Staff Change" - new PR?

**Comment by Keanu73** [comment]
> 
> 
> @Keanu73 that is not a "Training Staff Change" - new PR?

Fair enough, was just thinking it would be more convenient to slip it in here.

**Comment by inventor02** [comment]
data is from a different source

**Pull request merged**
