### PR TITLE
[WIP/TESTING] Sync bans to forum/ts

### LINKED ISSUE #945: Sync Bans With Forum
Appears to have been started in /app/Listeners/Sync/PushToForum.php
Updates to accounts passed through /app/Console/Commands/SyncCommunity.php

We need to ensure that when an account is suspended/unsuspended in Core (either as a result of a Local Ban or a Network Suspension) that this is passed through to the forum instantly.

Create onBanCreate and onBanRepeal listeners.

### PR DESCRIPTION
**Pull request by atoff**
Simply sync a local ban/network ban to the forum account, and also handle the end of the ban/repeal.

Also added in a listener to run the TeamSpeak manager when a user is banned, thus instantly removing them from the server.

Closes #945 & #946

### CODE REVIEW

**Comment by atoff** [comment]
@NFarrington I think this is now ready to be tested on a development environment if able?

**Comment by NFarrington** [comment]
I'll see what can/can't be tested in development and let you know if there are any issues.

Ideally syncing to TeamSpeak would use a new job specifically to kick the user if they are present, rather than running a full sync (which already runs every few minutes)

**Comment by NFarrington** [comment]
The code will be easier to manage and maintain with less duplication if we merge PushBanToForum and PushRepealToForum into the same listener (e.g. SyncBanToForum), which can do a simple check on the $event->ban to see if it's in effect.

It might make sense to have one listener that will sync an account to the forum, rather than just the ban, so that the same listener can be used for when other aspects are updated, e.g. states, and qualifications.

**Comment by atoff** [comment]
@NFarrington I have combined these listeners now; looking forward it would be nice to make use of the Account Touched event and sync like that, but the core functionality that we need is there now, and I will log an issue to look at syncing the whole account when touched.

**Comment by NFarrington** [comment]
The listeners for syncing to different services should remain separate (which is a key reason why it's possible to add multiple listeners to a single event) - it was only the PushBanToForum and PushRepealToForum listeners that should be merged into SyncBanToForum, or something similar. Since the code to ban and unban a forum user is almost identical, that's why it makes sense to have those in one listener.

Similarly, the listener could sync the entire account to the forum, because it's also very similar code, pushing to the same service. The listener should only be concerned with the forum, and use a separate listener for pushing to/syncing with TeamSpeak.

So, just to confirm, there should be one listener for each service, not one listener for each event. It may be that one listener is associated with multiple events.

**Comment by atoff** [comment]
Ah ok that makes a bit more sense - I will look into making the listener/event pairing for Account Touched work in a later PR, because at the moment the Account Touched event doesn't seem to be implemented.

**Pull request merged**
