### PR TITLE
Fix Unauthenticated Redirect

### PR DESCRIPTION
**Pull request by atoff**

### CODE REVIEW

**Review by CalumTowers — COMMENTED** [review]
Thanks @atoff. Looking at it now, I'm wondering whether the route name needs to be login rather than dashboard so it's explicit?

**Comment by atoff** [comment]
> Thanks @atoff. Looking at it now, I'm wondering whether the route name needs to be login rather than dashboard so it's explicit?

We can't name it login without changing the route name of the "actual" login route. Could rename to "landing" as that might make more sense>

**Comment by CalumTowers** [comment]
> > Thanks @atoff. Looking at it now, I'm wondering whether the route name needs to be login rather than dashboard so it's explicit?
> 
> 
> 
> We can't name it login without changing the route name of the "actual" login route. Could rename to "landing" as that might make more sense>

Agree that makes sense

**Review by CalumTowers — APPROVED** [review]

**Pull request merged**
