### PR TITLE
CORE-336 - Events on Booking Sidebar

### PR DESCRIPTION
**Pull request by atoff**
image

Without event:

image

Closes CORE-336

### CODE REVIEW

**Comment by atoff** [comment]
@daviesnathan are you happy if I just change the colour of this to the same as the button, and leave it like this (we can always change later!)

image

**Comment by CalumTowers** [comment]
@daviesnathan @atoff Who is working on this at the moment?

**Comment by atoff** [comment]
@CalumTowers I think this is probably good to go. It has been sitting here for too long, it was originally only a question of the colour for the event but I think I have found an acceptable compromise above.

**Comment by CalumTowers** [comment]
> @CalumTowers I think this is probably good to go. It has been sitting here for too long, it was originally only a question of the colour for the event but I think I have found an acceptable compromise above.

Agreed! Can you resolve conflicts and then merge? :)

**Pull request merged**
